apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-c2
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3
    ssh:
      allow: true
