---
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  shareProcessNamespace: true
  containers:
    - name: test
      image: docker.io/bradgeesaman/registry-search-order:latest
      #image: docker.io/library/nginx:latest
